//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntiEspais
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitatsConcedides
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivitatsConcedides()
        {
            this.Horari_activitat = new HashSet<Horari_activitat>();
            this.Horari = new HashSet<Horari>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int id_horari { get; set; }
        public byte competicio { get; set; }
        public int id_espai { get; set; }
        public int id_equip { get; set; }
        public int id_usuari { get; set; }
    
        public virtual ActivitatsDemanades ActivitatsDemanades { get; set; }
        public virtual Equip Equip { get; set; }
        public virtual Espai Espai { get; set; }
        public virtual Usuaris Usuaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horari_activitat> Horari_activitat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horari> Horari { get; set; }
    }
}
