//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntiEspais
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equip()
        {
            this.ActivitatsConcedides = new HashSet<ActivitatsConcedides>();
            this.ActivitatsDemanades = new HashSet<ActivitatsDemanades>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int id_esport { get; set; }
        public int id_entitat { get; set; }
        public int id_competicio { get; set; }
        public int id_categoriaEdat { get; set; }
        public int id_categoria { get; set; }
        public int id_sexe { get; set; }
        public int id_espai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitatsConcedides> ActivitatsConcedides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitatsDemanades> ActivitatsDemanades { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual CategoriaEdat CategoriaEdat { get; set; }
        public virtual Competicio Competicio { get; set; }
        public virtual Entitat Entitat { get; set; }
        public virtual Espai Espai { get; set; }
        public virtual Esport Esport { get; set; }
        public virtual Sexe Sexe { get; set; }
    }
}
