//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntiEspais
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horari_Instal_lacio
    {
        public int id { get; set; }
        public System.TimeSpan hora_inici { get; set; }
        public System.TimeSpan hora_final { get; set; }
        public int id_instal_lacio { get; set; }
        public int id_dia { get; set; }
    
        public virtual Dia Dia { get; set; }
        public virtual Instal_lacio Instal_lacio { get; set; }
    }
}
