//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntiEspais
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntiEspaisEntities1 : DbContext
    {
        public EntiEspaisEntities1()
            : base("name=EntiEspaisEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivitatsConcedides> ActivitatsConcedides { get; set; }
        public virtual DbSet<ActivitatsDemanades> ActivitatsDemanades { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CategoriaEdat> CategoriaEdat { get; set; }
        public virtual DbSet<Competicio> Competicio { get; set; }
        public virtual DbSet<Dia> Dia { get; set; }
        public virtual DbSet<Durada> Durada { get; set; }
        public virtual DbSet<Entitat> Entitat { get; set; }
        public virtual DbSet<Equip> Equip { get; set; }
        public virtual DbSet<Espai> Espai { get; set; }
        public virtual DbSet<Esport> Esport { get; set; }
        public virtual DbSet<Horari> Horari { get; set; }
        public virtual DbSet<Horari_activitat> Horari_activitat { get; set; }
        public virtual DbSet<Horari_ActivitatDemanda> Horari_ActivitatDemanda { get; set; }
        public virtual DbSet<Horari_Instal_lacio> Horari_Instal_lacio { get; set; }
        public virtual DbSet<Instal_lacio> Instal_lacio { get; set; }
        public virtual DbSet<Sexe> Sexe { get; set; }
        public virtual DbSet<Telefon> Telefon { get; set; }
        public virtual DbSet<Usuaris> Usuaris { get; set; }
    }
}
